# Generated by Django 4.2.3 on 2023-08-09 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Errand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('address_1', models.CharField(max_length=500)),
                ('address_2', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 12, 58, 469736, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('pending', '수락 대기'), ('in_progress', '진행 중'), ('completed', '완료')], default='수락 대기', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_errands', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_errands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
