# Generated by Django 4.2.3 on 2023-08-11 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 11, 31, 1, 398668, tzinfo=datetime.timezone.utc)),
        ),
    ]
