# Generated by Django 4.2.3 on 2023-08-12 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0003_alter_errand_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 2, 47, 54, 509193, tzinfo=datetime.timezone.utc)),
        ),
    ]
