# Generated by Django 4.2.3 on 2023-08-13 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0005_alter_errand_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 17, 3, 35, 485935, tzinfo=datetime.timezone.utc)),
        ),
    ]
